export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

// SINGLE PRODUCT
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

// PRODUCT REVIEW

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

// GET PRODUCT LIST BY CATEGORY
export const PRODUCT_LIST_CATEGORY_REQUEST = "PRODUCT_LIST_CATEGORY_REQUEST";
export const PRODUCT_LIST_CATEGORY_SUCCESS = "PRODUCT_LIST_CATEGORY_SUCCESS";
export const PRODUCT_LIST_CATEGORY_FAIL = "PRODUCT_LIST_CATEGORY_FAIL";

export const FILTER_LIST_REQUEST = "FILTER_LIST_REQUEST";
export const FILTER_LIST_SUCCESS = "FILTER_LIST_SUCCESS";
export const FILTER_LIST_FAIL = "FILTER_LIST_FAIL";
